### ISSUE TITLE
✉️ Message to you, Alexander ✉️

### ISSUE THREAD

**Issue by ghost** [SashaVolohov/VH-DOS#1]
@SashaVolohov 
**Hi, Sasha!** Andrew told me about you, and your skills. Your **operating system** is simple and excellent, and you're younger than 16. I'm too love 1992-'98 x86 machines. Could I work with you? I know _Assembly language_, _C_, _Pascal_ very well. Also, I have advanced skills in _HTML 4_, _CSS3_, and basic level of _JavaScript_. At least, could I be an editor/an author of the webpage of **VH-DOS**?

**Comment by SashaVolohov** [comment]
@Diicorp95, hello. Sorry if there are mistakes in this text, my knowledge of English leaves much to be desired. If you want to take part in the development of VH-DOS, I do not mind.

**Comment by ghost** [comment]
OK, I see. Are you registered in Telegram?

**Comment by SashaVolohov** [comment]
@Diicorp95, no, I'm not registered there. But if you want to contact me through it, I can register.

**Comment by ghost** [comment]
Please,  register. It is so nice

**Comment by SashaVolohov** [comment]
@Diicorp95, sorry, I can't register. Maybe Discord?

**Comment by ghost** [comment]
Why? Try to using proxy. Nevertheless, add me to Discord: Diicorp95#3425

**Comment by SashaVolohov** [comment]
@Diicorp95, I sent a friend request in Discord, please accept.
