### ISSUE TITLE
Bugged screen mode

### ISSUE THREAD

**Issue by ghost** [SashaVolohov/VH-DOS#2]
[/setup/boot.asm](https://github.com/SashaVolohov/VH-DOS/blob/master/sources/setup/boot.asm):
**Bugged screen mode causes infinite loop**. Possible mistake at [/kernel/TxtPrint.asm](https://github.com/SashaVolohov/VH-DOS/blob/master/sources/kernel/TxtPrint.asm)

**Comment by SashaVolohov** [comment]
@Diicorp95, it's strange. I will try to solve the problem
