### ISSUE TITLE
Code requires a great bugfix

### ISSUE THREAD

**Issue by ghost** [SashaVolohov/VH-DOS#3]
At this moment, code isn't works well. Boot code on setup disk is incorrect.

**Comment by SashaVolohov** [comment]
And the system is normally installed, or something with the display?

**Comment by ghost** [comment]
Setup disk does nothing, like there's no disk at all.

**Comment by SashaVolohov** [comment]
Hm... It's strange. I will try check this.

**Comment by ghost** [comment]
That's a mistake in FAT12 BPB, I guess..

**Comment by ghost** [comment]
I have this thought since last month: **The problem is considered in ORG offsets. They're not useful at this moment, while they should be. Memory address/jump address + offset = real memory address**
